### ISSUE TITLE
Is project dead and abandoned?

### ISSUE THREAD

**Issue by majkrzak** [haskell-webdriver/haskell-webdriver#184]
I was trying to use this in my project, but encountered many problems. (comparing to the python library)
- requirement of selenium server running,
- using extremally old version of this server
- firefox not starting even so

I also see 9 dangling pull-requests and two dozens of issues where no attention have ben taken. Did @kallisti-dev abandoned it? Should someone adopt it in such case, as the library looks extremely useful.

**Comment by georgefst** [comment]
I've just ported a project to `webdriver-w3c` for many of these reasons. See https://github.com/nbloomf/webdriver-w3c/issues/19#issuecomment-1100296831.
