### ISSUE TITLE
`webdriver` has a build failure with `aeson-2.2.0.0`

### ISSUE THREAD

**Issue by MorrowM** [haskell-webdriver/haskell-webdriver#193]
The build fails due to the removal of `Data.Aeson.Parser`.
```
src/Test/WebDriver/Firefox/Profile.hs:33:1: error:
    Could not find module ‘Data.Aeson.Parser’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
33 | import Data.Aeson.Parser (jstring, value')
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Perhaps a Hackage package revision can be made adding an upper bound?

**Comment by thomasjm** [comment]
Okay, I added the revision to release `0.11.0.0`.

FWIW I got it building in this branch: https://github.com/haskell-webdriver/haskell-webdriver/tree/aeson-2.2-support

Aeson 2.2 moves some functionality to the `attoparsec-aeson` package. Not sure if we can conditionally require that or something with Cabal.

**Comment by NorfairKing** [comment]
Let's merge this if it works?

**Comment by thomasjm** [comment]
Released in `0.12.0.0`

**Comment by NorfairKing** [comment]
@thomasjm it's not on master yet, it seems, is that on purpose?

**Comment by thomasjm** [comment]
Oops, that was a master/main confusion. Done now
