### ISSUE TITLE
setLocation is missing a field

### ISSUE THREAD

**Issue by NorfairKing** [haskell-webdriver/haskell-webdriver#197]
Here's the proper implementation:

```
setLocation' :: (Int, Int, Int) -> WebdriverTestM app ()
setLocation' (lat, lon, alt) =             
  WD.ignoreReturn $  
    WD.doSessCommand "POST" "/location" $   
      object                            
        [ "location"                   
            .= object
              [ "longitude" .= lon,
                "latitude" .= lat,  
                "altitude" .= alt
              ]                                   
        ]
```

**Comment by thomasjm** [comment]
Thanks! Any chance you could write a test for this one?

My goal is to get all the commands in this library tested. The beginnings of this are here: https://github.com/haskell-webdriver/haskell-webdriver/tree/main/tests/Spec.

I think this fix has already been made actually in the `dev` branch, where I've been doing a bunch of modernization work and which I've just merged into `main`. (Although I'd rather replace this `(Int, Int, Int)` with an actual data type...)

**Comment by NorfairKing** [comment]
Hi @thomasjm Thank you so much for your efforts in modernising this library! I don't have any more to donate. I just wanted to let you know that I'm using a fixed version of one of the functions :)

**Comment by thomasjm** [comment]
Okay, closing as complete (although beware lat/long are flipped).
