### ISSUE TITLE
PhantomJS Support

### ISSUE THREAD

**Issue by codygman** [haskell-webdriver/haskell-webdriver#62]
What would be necessary? Anything to keep in mind?

If I decided to try and add this, would I be able to just model the Chrome module? Upon looking at the Chrome module, it looks like not much is in there.

Any direction is appreciated.

**Comment by agreif** [comment]
thanks for this thread, it helped me a lot.
For completeness, here is a small config how to do this, with the most simple settings:

start phantomjs on the default selenium port
```bash
$ phantomjs --webdriver=127.0.0.1:4444
```

in the haskell code (defaults to localhost on port 444):
```haskell
myConfig :: WDConfig
myConfig = defaultConfig
main :: IO ()
main = runSession myConfig $ do ...
```

Alex.
